/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jgen;

import java.util.ArrayList;
import java.util.Arrays;

import org.stringtemplate.v4.ST;
import org.stringtemplate.v4.STGroupFile;

public final class App {
    public static void main(String[] args) {
        STGroupFile groupFile = new STGroupFile(App.class.getClassLoader()
            .getResource("jgen/cout.stg"));

        ST cb = groupFile.getInstanceOf("unit_body");
        UnitDef unit = new UnitDef();
        unit.setName("myunit");
        unit.setImports(Arrays.asList("miod_sys"));
        ProcDef proc = new ProcDef();
        proc.setName("my_proc");
        ClassDef cls = new ClassDef();
        cls.setName("MyClass");
        ClassDef cls2 = new ClassDef();
        cls2.setName("MyClass2");
        unit.setClasses(Arrays.asList(cls, cls2));
        cb.add("unit", unit);
        System.out.print(cb.render());
    }
}
