/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jgen;

import java.util.ArrayList;

import org.stringtemplate.v4.ST;
import org.stringtemplate.v4.STGroupFile;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        /*
        System.out.println(new App().getGreeting());
        ST hello = new ST("Hello, <name>!");
        hello.add("name", "World");
        String output = hello.render();
        System.out.println(output);
        */

        STGroupFile groupFile = new STGroupFile(App.class.getClassLoader()
            .getResource("jgen/cout.stg"));

        ST cb = groupFile.getInstanceOf("unit_body");
        UnitDef unit = new UnitDef();
        unit.setName("myunit");
        ClassDef cls = new ClassDef();
        cls.setName("MyClass");
        ProcDef proc = new ProcDef();
        proc.setName("my_proc");
        ArrayList<ClassDef> classes = new ArrayList<>();
        classes.add(cls);
        ClassDef cls2 = new ClassDef();
        cls2.setName("MyClass2");
        classes.add(cls2);
        unit.setClasses(classes);
        cb.add("unit", unit);
        System.out.print(cb.render());
    }
}
