/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package miod_parser;

import java.io.IOException;
import java.util.logging.Logger;

import org.antlr.v4.runtime.tree.ParseTree;
import org.junit.Test;
import org.miod.parser.ParsingErrorListener;
import static org.junit.Assert.*;

public class ParsingTests {
    private final static Logger LOGGER = Logger.getLogger(ParsingTests.class.getName());

    @Test
    public void testSyntax1() throws IOException {
        ParsingErrorListener errListener = new ParsingErrorListener();
        ParseTree tree = TestUtils.parseSyntax(TestUtils.getStreamFromResource("t1.miod"), errListener);
        assertTrue(tree != null);
    }

}
