/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package miod_parser;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.logging.Logger;

import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeWalker;
import org.junit.Test;
import org.miod.ast.Comment;
import org.miod.ast.Doc;
import org.miod.compiler.BuildContextImpl;
import org.miod.parser.AstBuilder;
import org.miod.parser.ParserUtils;
import org.miod.parser.ParsingErrorListener;
import org.miod.parser.generated.MiodBaseListener;
import org.miod.parser.generated.MiodParser.CommentsContext;
import org.miod.parser.generated.MiodParser.DocsContext;
import org.miod.parser.generated.MiodParser.UnitHeaderContext;

public class ParsingTests {
    private final static Logger LOGGER = Logger.getLogger(ParsingTests.class.getName());

    static class MyParseTreeListener extends MiodBaseListener {
        public String pkgName = "";
        public final List<String> comments = new ArrayList<>();
        public final List<String> docs = new ArrayList<>();

        MyParseTreeListener() {
        }

        @Override
        public void exitUnitHeader(UnitHeaderContext ctx) {
            pkgName = ctx.fullId().getText();
        }

        @Override
        public void exitComments(CommentsContext ctx) {
            comments.add(ctx.getText());
        }

        @Override
        public void exitDocs(DocsContext ctx) {
            docs.add(ctx.getText());
        }
    }

    @Test
    public void testSyntax1() throws IOException {
        ParsingErrorListener errListener = new ParsingErrorListener();
        ParseTree tree = ParserUtils.parseSyntax(ParserUtils.getStreamFromResource("t1.miod"), errListener);

        assertNotNull(tree);
        assertTrue(errListener.getErrors().isEmpty());

        MyParseTreeListener listener = new MyParseTreeListener();
        ParseTreeWalker.DEFAULT.walk(listener, tree);

        assertEquals("t1", listener.pkgName);
        assertEquals("# comments1\n", listener.comments.get(0));
        assertEquals("## docs1\n## doc1 line2\n", listener.docs.get(0));
    }

    @Test
    public void testAstBuilder() throws IOException, MalformedURLException, URISyntaxException {
        ParsingErrorListener errListener = new ParsingErrorListener();
        URL url = ParserUtils.getUrlFromResource("t1.miod");
        Path unitPath = Paths.get(url.toURI());
        LOGGER.info(unitPath.toString());

        ParseTree tree = ParserUtils.parseSyntax(Files.newInputStream(unitPath), errListener);

        assertTrue(errListener.getErrors().isEmpty());

        AstBuilder builder = new AstBuilder();
        builder.parse(tree, unitPath);
        LOGGER.info(builder.getRoot().getName());
        assertEquals("t1", builder.getRoot().getName());
        Comment comments = (Comment) builder.getRoot().getSubnodes().get(0);
        Doc docs = (Doc) builder.getRoot().getSubnodes().get(1);
        assertEquals("# comments1\n", comments.getText());
        assertEquals("## docs1\n## doc1 line2\n", docs.getText());
    }

    @Test
    public void testBuildContextImplUnitPath() throws URISyntaxException {
        URL url = ParserUtils.getUrlFromResource("t1.miod");
        Path t1Path = Path.of(url.toURI());
        Path t1Root = t1Path.getParent();
        List<Path> importPaths = new ArrayList<>();
        List<Path> sources = new ArrayList<>();
        sources.add(t1Path);
        importPaths.add(t1Root);
        BuildContextImpl ctx = new BuildContextImpl(new HashSet<>(), importPaths, sources, Paths.get(""));
        Optional<Path> unitPath = ctx.unitPathFromName("t1");
        assertTrue(unitPath.isPresent());
        assertEquals(t1Path, unitPath.get());
        Optional<Path> unitPath2 = ctx.unitPathFromName("nonexisting::aa");
        assertFalse(unitPath2.isPresent());
        Optional<Path> unitPath3 = ctx.unitPathFromName("pkgns::t2");
        assertTrue(unitPath3.isPresent());
    }

}
